Repository MyCoRe-Org/mycore, pull requests merged in 2023-11, with the labels that each got.

#2003 MCR-2990 Support mcrwebpage:xinclude in xslt/MyCoReWebPage.xsl
  mycore-base/src/main/resources/xslt/MyCoReWebPage.xsl
Labels: ready to merge

#1971 MCR-2978 Added org.mycore.services.i18n.MCRTranslation.translate(java…
  mycore-base/src/main/java/org/mycore/common/MCRJSONUtils.java
  mycore-base/src/main/java/org/mycore/frontend/cli/MCRDeveloperCommands.java
  mycore-base/src/main/java/org/mycore/services/i18n/MCRTranslation.java
  mycore-base/src/test/java/org/mycore/services/i18n/MCRTranslationTest.java
  mycore-restapi/src/main/java/org/mycore/restapi/v1/MCRRestAPIMessages.java
Labels: important, ready to merge

#1994 MCR-2994 Added some validation to org.mycore.common.xml.MCRXMLFunctions.isCategoryID(String, String)
  mycore-base/src/main/java/org/mycore/common/xml/MCRXMLFunctions.java
  mycore-base/src/main/java/org/mycore/datamodel/classifications2/MCRCategoryID.java
Labels: ready to merge

#2011 MCR-3004 Message of MCRAccessException is ill-formatted and has a typo
  mycore-base/src/main/java/org/mycore/access/MCRAccessException.java
Labels: important

#2015 merge 2022.06.x into 2023.06.x
  mycore-base/src/main/java/org/mycore/common/MCRJSONUtils.java
  mycore-base/src/main/java/org/mycore/frontend/cli/MCRDeveloperCommands.java
  mycore-base/src/main/java/org/mycore/services/i18n/MCRTranslation.java
  mycore-base/src/test/java/org/mycore/services/i18n/MCRTranslationTest.java
  mycore-mods/src/main/java/org/mycore/mods/MCRMODSEmbargoUtils.java
  mycore-restapi/src/main/java/org/mycore/restapi/v1/MCRRestAPIMessages.java
Labels: important

#2016 merge 2023.06.x into main
  mycore-base/src/main/java/org/mycore/access/MCRAccessException.java
  mycore-base/src/main/java/org/mycore/common/MCRJSONUtils.java
  mycore-base/src/main/java/org/mycore/common/content/transformer/MCRXsonifyTransformer.java
  mycore-base/src/main/java/org/mycore/common/xml/MCRXMLFunctions.java
  mycore-base/src/main/java/org/mycore/datamodel/classifications2/MCRCategoryID.java
  mycore-base/src/main/java/org/mycore/frontend/cli/MCRBasicCommands.java
  mycore-base/src/main/java/org/mycore/frontend/cli/MCRDeveloperCommands.java
  mycore-base/src/main/java/org/mycore/services/i18n/MCRTranslation.java
  mycore-base/src/main/resources/xslt/MyCoReWebPage.xsl
  mycore-base/src/test/java/org/mycore/services/i18n/MCRTranslationTest.java
  mycore-bom/pom.xml
  mycore-mods/src/main/java/org/mycore/mods/MCRMODSEmbargoUtils.java
  mycore-restapi/src/main/java/org/mycore/restapi/v1/MCRRestAPIMessages.java
Labels: important

#2018 MCR-3008 update schema in persistence.xml/remove mycore-jpa-defaults.xml
  mycore-acl/src/test/resources/META-INF/persistence.xml
  mycore-base/src/main/resources/configdir.template/resources/META-INF/mycore-jpa-defaults.xml
  mycore-base/src/main/resources/configdir.template/resources/META-INF/persistence.xml
  mycore-base/src/test/resources/META-INF/persistence.xml
  mycore-cronjob/src/test/resources/META-INF/persistence.xml
  mycore-ifs/src/test/resources/META-INF/persistence.xml
  mycore-jobqueue/src/test/resources/META-INF/persistence.xml
  mycore-mods/src/test/resources/META-INF/persistence.xml
  mycore-neo4j/src/test/resources/META-INF/persistence.xml
  mycore-orcid2/src/test/resources/META-INF/persistence.xml
  mycore-packer/src/test/resources/META-INF/persistence.xml
  mycore-pi/src/test/resources/META-INF/persistence.xml
  mycore-user2/src/test/resources/META-INF/persistence.xml
Labels: important

#2019 MCR-3009 update dependency - image-tiler 4.0
  mycore-bom/pom.xml
Labels: important

#2020 MCR-2981 replace deprecated method checkPermissionForReadingDerivate()
  mycore-media/src/main/java/org/mycore/media/frontend/jersey/MCRThumbnailResource.java
Labels: important
